included:
  - Sources
  - Tests

excluded:
  - .build
  - .worktrees
  - docs
  - node_modules
  - public
  - examples

opt_in_rules:
  - empty_count
  - explicit_init
  - fatal_error_message
  - first_where
  - redundant_nil_coalescing
  - sorted_first_last
  - vertical_parameter_alignment_on_call

disabled_rules:
  - cyclomatic_complexity
  - function_body_length
  - line_length

identifier_name:
  min_length:
    warning: 2
  excluded:
    - id
    - i
    - x
    - y
    - rc

force_cast: warning
force_try: warning
trailing_whitespace:
  ignores_empty_lines: true

reporter: "xcode"
